- name:  install apache # Name of the playbook
  hosts: web # name of teh target
  become: yes # if we need root used to do this task
  
  vars:
    apache_port: 80
    apache_source_path: /home/ec2-user/learning/index.html
    apache_dest_path: /var/www/html/

  tasks:
    - name: Install the apache
      dnf:
        name: httpd
        state: present
      tags:
        - control
    - name: Start the apache
      service:
        name: httpd
        state: started
      tags:
       - start

    - name: Copy file from controller to target
      copy:
        src: "{{ apache_source_path }}"
        dest: "{{ apache_dest_path }}"
    - name: Ensure the default Apache port is "{{ apache_port }}"
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: "Listen {{ apache_port }}"
      notify: ReStart the apache11
  handlers:
    - name: ReStart the apache11
      service:
        name: httpd
        state: restarted
